#!/bin/bash

export WILDENV_ROOT_DIR=${WILDENV_ROOT_DIR:-$HOME/.wildenv}
WILDENV_SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"

export PATH="${WILDENV_ROOT_DIR}/bin:$PATH"

if [[ ! -f "${WILDENV_ROOT_DIR}" ]]; then
  mkdir -p "${WILDENV_ROOT_DIR}/"{bin,etc/bash/{completion,key-bindings},man}
  python3 -m venv "${WILDENV_ROOT_DIR}/python"
  for module in shelltools; do
    "${WILDENV_SCRIPT_DIR}/modules/${module}/setup.sh"
  done
fi

for module in shelltools; do
  . "${WILDENV_SCRIPT_DIR}/modules/${module}/bashrc.sh"
done
