#!/bin/bash

export WILDENV_ROOT_DIR=${WILDENV_ROOT_DIR:-$HOME/.wildenv}
WILDENV_SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"

action=$1

function usage() {
  echo "$(basename "$0") [setup]"
}

case $action in
setup)
  if [[ ! -f "${WILDENV_ROOT_DIR}" ]]; then
    mkdir -p "${WILDENV_ROOT_DIR}/"{bin,etc/bash/{completion,key-bindings},man}
    python3 -m venv "${WILDENV_ROOT_DIR}/python"

    IFS=':' read -r -a _modules <<< "${WILDENV_MODULES}"
    IFS=':' read -r -a _modules_dirs <<< "${WILDENV_MODULES_DIRS}"

    for _module in "${_modules[@]}"; do
      _module_found=1
      for _modules_dir in "${_modules_dirs[@]}"; do
        if [[ -d "${_modules_dir}/modules/${_module}" ]]; then
          "${_modules_dir}/modules/${_module}/setup.sh"
          _module_found=0
          break
        fi
      done
      if [[ $_module_found -eq 1 ]]; then
        printf 'Module %s not found.\n' $_module
      fi
    done
    
  else
    printf "Directory %s already exists." "${WILDENV_ROOT_DIR}"
  fi
  ;;
dep)
  sudo apt-get update
  sudo apt-get install -y python3-venv curl git git-crypt gnupg fonts-powerline
  mkdir -p "${WILDENV_ROOT_DIR}/tmp/" "$HOME/.local/share/fonts/."
  git clone https://github.com/powerline/fonts "${WILDENV_ROOT_DIR}/tmp/fonts"
  git clone https://github.com/abertsch/Menlo-for-Powerline "${WILDENV_ROOT_DIR}/tmp/fonts2"
  cp "${WILDENV_ROOT_DIR}"/tmp/fonts2/*.ttf "$HOME/.local/share/fonts/."
  "${WILDENV_ROOT_DIR}/tmp/fonts/install.sh"
  rm -rf "${WILDENV_ROOT_DIR}/tmp/fonts"
  ;;
*)
  usage
  exit 1
esac