#!/bin/bash

export WILDENV_ROOT_DIR=${WILDENV_ROOT_DIR:-$HOME/.wildenv}
WILDENV_SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"

if [[ ! -d "${WILDENV_ROOT_DIR}" ]]; then
  echo "Wildenv not configured !"
else
  export PATH="${WILDENV_ROOT_DIR}/bin:$PATH"
  for module in shelltools kubernetes; do
    . "${WILDENV_SCRIPT_DIR}/modules/${module}/bashrc.sh"
  done
fi
