#!/bin/bash

export WILDENV_ROOT_DIR=${WILDENV_ROOT_DIR:-$HOME/.wildenv}
WILDENV_SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"

export WILDENV_MODULES_DIRS=${WILDENV_MODULES_DIRS:-"${WILDENV_SCRIPT_DIR}"}
export WILDENV_MODULES=${WILDENV_MODULES:-shelltools:kubernetes}

if [[ ! -d "${WILDENV_ROOT_DIR}" ]]; then
  echo "Wildenv not configured !"
else
  if ! [[ "$PATH" =~ "${WILDENV_ROOT_DIR}/bin" ]]; then
    export PATH="${WILDENV_ROOT_DIR}/bin:$PATH"
  fi

  IFS=':' read -r -a _modules <<< "${WILDENV_MODULES}"
  IFS=':' read -r -a _modules_dirs <<< "${WILDENV_MODULES_DIRS}"

  for _module in "${_modules[@]}"; do
    _module_found=1
    for _modules_dir in "${_modules_dirs[@]}"; do
      if [[ -d "${_modules_dir}/modules/${_module}" ]]; then
        [[ -f "${_modules_dir}/modules/${_module}/bashrc.sh" ]] && . "${_modules_dir}/modules/${_module}/bashrc.sh"
        _module_found=0
        break
      fi
    done
    if [[ $_module_found -eq 1 ]]; then
      printf 'Module %s not found.\n' $_module
    fi
  done
fi
