#!/bin/bash

export WILDENV_ROOT_DIR=${WILDENV_ROOT_DIR:-$HOME/.wildenv}
WILDENV_SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"

action=$1

function usage() {
  echo "$(basename "$0") [setup]"
}

case $action in
setup)
  if [[ ! -f "${WILDENV_ROOT_DIR}" ]]; then
    mkdir -p "${WILDENV_ROOT_DIR}/"{bin,etc/bash/{completion,key-bindings},man}
    python3 -m venv "${WILDENV_ROOT_DIR}/python"
    for module in shelltools git kubernetes; do
      "${WILDENV_SCRIPT_DIR}/modules/${module}/setup.sh"
    done
  else
    printf "Directory %s already exists." "${WILDENV_ROOT_DIR}"
  fi
  ;;
dep)
  sudo apt-get update
  sudo apt-get install -y python3-venv curl git git-crypt gnupg
  ;;
*)
  usage
  exit 1
esac